dist: xenial
language: java
jdk:
- openjdk8
cache:
  directories:
  - "~/mycache"
  - "$HOME/.m2/repository"
before_install:
- chmod +x mvnw
install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.7/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
sudo: required
services:
- docker
jobs:
  include:
  - stage: BUILD MAVEN ARTIFACT
    script:
    - "./mvnw clean install -DskipTests"
    - cp ./gameoflife-web/target/gameoflife.war ~/mycache
    
  - stage: JUNIT TEST EXECUTION
    script:
    - "./mvnw test -B"
    
  - stage: NEXUS_ARTIFACT_PUSH
    script:
    - mvn deploy --settings travis.settings.xml
    on:
      branch: master
      
  - stage: BUILD & PUSH DOCKER IMAGE
    script:
    - cp ~/mycache/gameoflife.war .
    - docker build -t "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT} .
    - docker tag "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}  "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}
    - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
    
  - stage: DEPLOY ON K8S CLUSTER
    script:
    - mkdir ${HOME}/.kube
    - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
    - kubectl apply -f travis_ci_demo.yml
  
  

  

# safelist
branches:
  only:
  - master
  - test1

  
#deploy:
#  provider: script
 # script: mvn deploy --settings travis.settings.xml
 # on:
 #   branch: master
 
notifications:
  email: rghorpade80@gmail.com
